from __future__ import absolute_import

from parser.elmo_network import ElmoNetwork
from parser.parser_network import ParserNetwork
from parser.tagger_network import TaggerNetwork
from parser.graph_parser_network import GraphParserNetwork
from parser.srl_parser_network import SrlParserNetwork
from parser.unfactor_graph_parser_network import UnfactorGraphParserNetwork
from parser.second_order_network import SecondOrderNetwork
from parser.argument_detection_network import ArgumentDetectionNetwork
# from parser.trigraph_parser_network import TriGraphParserNetwork
